### ISSUE TITLE
Admin Spectate Script errors out

### ISSUE THREAD

**Issue by BryanBoru** [TFT8/missions#1]
maybe we could work in a different one or fix the error that pops, I can seem to solve it. 

When spectator is called on [Admin call](https://github.com/TFT8/Missions/blob/master/public/co61_AW_I%26A_TFTEdit.Altis/scripts/admin_uid.sqf#L10) it errors out saying a sub-[config](https://github.com/TFT8/Missions/blob/master/public/co61_AW_I%26A_TFTEdit.Altis/scripts/spectator/specta.sqf#L1) is missing

**Comment by BryanBoru** [comment]
Possibly switch to BIS or more modern spectate?

**Comment by theYoursTruly** [comment]
Changed to ACE Spectate
