### ISSUE TITLE
Do we reply on Sling-load script or switch to vanilla?

### ISSUE THREAD

**Issue by BryanBoru** [TFT8/missions#2]

**Comment by ampersand38** [comment]
Do we currently use a sling-load script? I think vanilla is fine. If we're talking about public mission, we can just deploy 1 or 2 heavy vehicles at a few of the vehicle service points or "beachheads" around the map, making it a <5km drive to any AO.

**Comment by BryanBoru** [comment]
@ampersand38  you mentioned this idea, and overall I like it but am concerned for it being buggy, do you think you can create a sample mission if you had a process in mind? 
If you didn't have a specific means in mind, @firemat05 and S3 et all can brainstorm the best (efficient low intensive) way to do this or an alternative.
