### ISSUE TITLE
[I&A] Plane Service Point doesn't support UAVs correctly

### ISSUE THREAD

**Issue by theYoursTruly** [TFT8/missions#6]
Service point at the end of runway doesn't rearm (plane) UAVs.

## Expected Behavior (required)
When stopping on Plane Service Point UAV should be rearmed and refueled.

## Current Behavior (required)
Ammo and fuel is taken out, but nothing happens afterwards.

## Possible Solution
Double-check https://github.com/TFT8/Missions/blob/master/public/co61_AW_I%26A_TFTEdit.Altis/scripts/misc/rearmPlane.sqf

## Steps to Reproduce (for bugs)
1. Connect to Greyhawk
2. Drive to service point and stop

**Comment by theYoursTruly** [comment]
After longer investigation I noticed that problem occurs only if person disconnects from a UAV while it's being serviced. That may be happening because operator can't see messages about servicing. Replacing `_veh vehicleChat` with `systemChat` should solve that problem.

**Comment by ampersand38** [comment]
Seems to work in both single and multiplayer, with disconnect from UAV.

**Comment by theYoursTruly** [comment]
Doesn't apply to the new I&A version.
